### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [pureport/pureport-python-client#30]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.7. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pureport-client -w /tmp/ext pureport-client==1.0.7
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pureport-client==1.0.7
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/a03/24569d1fd70c7/pureport-client-1.0.7.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-k2wua8sr/pureport-client/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-k2wua8sr/pureport-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-k2wua8sr/pureport-client/pip-egg-info
         cwd: /tmp/pip-wheel-k2wua8sr/pureport-client/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-k2wua8sr/pureport-client/setup.py", line 39, in <module>
        install_requires=read_requirements('requirements.txt'),
      File "/tmp/pip-wheel-k2wua8sr/pureport-client/setup.py", line 13, in read_requirements
        reqs = read_file(file_name).splitlines()
      File "/tmp/pip-wheel-k2wua8sr/pureport-client/setup.py", line 7, in read_file
        with open(file_name, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kevinkirkup** [comment]
Thx! should be fixed shortly.
